"""Creacion de Accesorio

Revision ID: 2dbc78b509a8
Revises: 98ba559cf272
Create Date: 2024-08-11 18:14:12.332889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbc78b509a8'
down_revision = '98ba559cf272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_accesorio', sa.String(length=50), nullable=False),
    sa.Column('tipo_accesorio2', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesorio')
    # ### end Alembic commands ###
