"""Creacion de Caracteristica

Revision ID: 98ba559cf272
Revises: 2719348e9e83
Create Date: 2024-08-09 17:48:04.041315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ba559cf272'
down_revision = '2719348e9e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tamanio_pantalla', sa.String(length=50), nullable=False),
    sa.Column('capacidad_bateria', sa.String(length=50), nullable=False),
    sa.Column('camara', sa.String(length=50), nullable=False),
    sa.Column('memoria', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caracteristica')
    # ### end Alembic commands ###
