"""Creacion de Fabricante

Revision ID: b68674155a30
Revises: 2c10cb512e8f
Create Date: 2024-08-07 19:33:20.393934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68674155a30'
down_revision = '2c10cb512e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_fabricante', sa.String(length=50), nullable=False),
    sa.Column('pais_origen', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fabricante')
    # ### end Alembic commands ###
